#Parte 1#

name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build, Teste e Criação de Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar Dependências
        run: npm install

      - name: Executar Testes Unitários
        run: npm test

      - name: Construir a Aplicação
        run: npm run build

#Parte 2#

      - name: Preparar Artefato para Release
        run: |
          mkdir -p build
          cp -R index.js app.js package.json build/

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./build

      - name: Criar Release no GitHub com o Artefato
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: v1.0.${{ github.run_number }}
          name: "Release v1.0.${{ github.run_number }}"
          body: "Release gerada para o commit ${{ github.sha }}"
          files: |
            ./build/**

        